services:
  frontend:
    build: ./forntend
    ports:
      - "3000:3000"
    volumes:
      - ./forntend:/usr/src/app
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development
